# docker-compose.yml

version: "3.7"
services:

  lobster-backend:
    build:
      context: .
    command: "wait-for-it db:5432 -- bash -c \"npm run migrate && pm2-runtime ./build/server.js\""
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
        - http
        - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - lobster-db:/var/lib/postgresql/data
    networks:
      - db

  caddy:
    image: caddy:2.1.1
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./secrets/certs:/root/certs
      - ./public:/public
    networks:
      - http
    ports:
      - "80:80"
      - "443:443"
        
volumes:
  lobster-db:

networks:
  http:
  db: